language: perl
perl:
  - "5.18"
  - "5.26"
  - "5.28"
env:
  - "HARNESS_OPTIONS=j9 TEST_ONLINE=mongodb://127.0.0.1:27017/minion"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4"
  - "echo 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverser' | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org"
install:
  - "cpanm -n --installdeps ."
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
notifications:
  email: false
